#
#   Runs multiple website on different ports
#
version: "3.9"

services:
  parallelsite:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - ./parallelism:/usr/share/nginx/html